
default: &default
  free: 100
  basic: 1000


Address:
  <<: *default
Article:
  <<: *default
ArticleGroup:
  <<: *default
Customer:
  <<: *default
DeviceFailureCategory:
  <<: *default
DeviceManufacturer:
  <<: *default
DeviceModel:
  <<: *default
Document:
  <<: *default
Issue:
  <<: *default
IssueEntry:
  <<: *default
RepairSet:
  <<: *default
RepairSetEntry:
  <<: *default
Stock:
  <<: *default
StockArea:
  <<: *default
StockLocation:
  <<: *default
StockMovement:
  <<: *default
Supplier:
  <<: *default
SupplierArticle:
  <<: *default
SupplierSource:
  <<: *default


ApiToken:
  free: 0
  basic: 10
Comment:
  free: 10_000
  basic: 10_000
Device:
  free: 10_000
  basic: 10_000
DeviceColor:
  free: 10_000
  basic: 10_000
Merchant:
  free: 1
  basic: 10
User:
  free: 1
  basic: 3
