name: default-mail-template
type: mail
subject: Wichtige Aktualisierung zu Ihrem Auftrag
protected: true
body: |
  <table
    class="body"
    style="
      border-collapse: separate;
      mso-table-lspace: 0pt;
      mso-table-rspace: 0pt;
      background-color: #f6f6f6;
      width: 100%;
    "
    role="presentation"
    border="0"
    width="100%"
    cellspacing="0"
    cellpadding="0"
    bgcolor="#f6f6f6"
  >
    <tbody>
      <tr>
        <td
          style="font-family: sans-serif; font-size: 14px; vertical-align: top"
          valign="top"
        >
          &nbsp;
        </td>
        <td
          class="container"
          style="
            font-family: sans-serif;
            font-size: 14px;
            vertical-align: top;
            display: block;
            max-width: 580px;
            padding: 10px;
            width: 580px;
            margin: 0 auto;
          "
          valign="top"
          width="580"
        >
          <div
            class="content"
            style="
              box-sizing: border-box;
              display: block;
              margin: 0 auto;
              max-width: 580px;
              padding: 10px;
            "
          >
            <!-- START CENTERED WHITE CONTAINER -->
            <table
              class="main"
              style="
                border-collapse: separate;
                mso-table-lspace: 0pt;
                mso-table-rspace: 0pt;
                background: #ffffff;
                border-radius: 3px;
                width: 100%;
              "
              role="presentation"
              width="100%"
            >
              <!-- START MAIN CONTENT AREA -->
              <tbody>
                <tr>
                  <td
                    class="wrapper"
                    style="
                      font-family: sans-serif;
                      font-size: 14px;
                      vertical-align: top;
                      box-sizing: border-box;
                      padding: 20px;
                    "
                    valign="top"
                  >
                    <table
                      style="
                        border-collapse: separate;
                        mso-table-lspace: 0pt;
                        mso-table-rspace: 0pt;
                        width: 100%;
                      "
                      role="presentation"
                      border="0"
                      width="100%"
                      cellspacing="0"
                      cellpadding="0"
                    >
                      <tbody>
                        <tr>
                          <td
                            style="
                              font-family: sans-serif;
                              font-size: 14px;
                              vertical-align: top;
                            "
                            valign="top"
                          >
                            <img
                              style="margin-bottom: 15px; height: 50px"
                              src="{{merchant.logo_url}}"
                              height="50px"
                            />
                          </td>
                        </tr>
                        <tr>
                          <td
                            style="
                              font-family: sans-serif;
                              font-size: 14px;
                              vertical-align: top;
                            "
                            valign="top"
                          >
                            <p
                              style="
                                font-family: sans-serif;
                                font-size: 14px;
                                font-weight: normal;
                                margin: 0;
                                margin-bottom: 15px;
                              "
                            >
                              Guten Tag {{customer.salutation}} {{customer.name}},
                            </p>
                            <p
                              style="
                                font-family: sans-serif;
                                font-size: 14px;
                                font-weight: normal;
                                margin: 0;
                                margin-bottom: 15px;
                              "
                            >
                              wir m&ouml;chten Ihnen mitteilen, dass wir Ihr
                              Dokument zu Ihrer Anfrage erstellt haben. <br />Das
                              Dokument ist der Anlage dieser E-Mail
                              beigef&uuml;gt.
                            </p>
                            <p
                              style="
                                font-family: sans-serif;
                                font-size: 14px;
                                font-weight: normal;
                                margin: 0;
                                margin-bottom: 15px;
                              "
                            >
                              Dein {{ merchant.company_name }} Team.
                            </p>
                            <p
                              style="
                                font-family: sans-serif;
                                font-size: 14px;
                                font-weight: normal;
                                margin: 0;
                                margin-bottom: 15px;
                              "
                            >
                              &nbsp;
                            </p>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </td>
                </tr>
                <!-- END MAIN CONTENT AREA -->
              </tbody>
            </table>
            <!-- END CENTERED WHITE CONTAINER -->
            <!-- START FOOTER -->
            <div
              class="footer"
              style="
                clear: both;
                margin-top: 10px;
                text-align: center;
                width: 100%;
              "
            >
              <table
                style="
                  border-collapse: separate;
                  mso-table-lspace: 0pt;
                  mso-table-rspace: 0pt;
                  width: 100%;
                "
                role="presentation"
                border="0"
                width="100%"
                cellspacing="0"
                cellpadding="0"
              >
                <tbody>
                  <tr>
                    <td
                      class="content-block powered-by"
                      style="
                        font-family: sans-serif;
                        vertical-align: top;
                        padding-bottom: 10px;
                        padding-top: 10px;
                        color: #999999;
                        font-size: 12px;
                        text-align: center;
                      "
                      align="center"
                      valign="top"
                    >
                      <a
                        style="
                          color: #999999;
                          font-size: 12px;
                          text-align: center;
                          text-decoration: none;
                        "
                        href="{{merchant.homepage}}"
                        >{{merchant.homepage}}</a
                      >.
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <!-- END FOOTER -->
          </div>
        </td>
        <td
          style="font-family: sans-serif; font-size: 14px; vertical-align: top"
          valign="top"
        >
          &nbsp;
        </td>
      </tr>
    </tbody>
  </table>

