name: default-calendar-confirmed-sms-template
type: sms
protected: true
body: |
  Hallo {{customer.name}}, Ihr Termin bei {{merchant.branch_name}} wurde best√§tigt. Wir erwarten Sie am {{calendar_entry.start_at}}.
