name: default-calendar-canceld-mail-template
type: mail
subject: Ihr Termin wurde storniert
protected: true
body: |
  <center style="width: 100%; background: #ffffff">
    <div style="max-width: 600px; margin: auto; padding: 0">
      <table
        style="border-collapse: collapse; max-width: 600px; margin: 0 auto"
        width="100%"
        align="center"
      >
        <tbody>
          <tr>
            <td style="padding: 30px 35px">
              <p style="margin: 0; color: #555555">
                Hallo {{customer.salutation}} {{customer.name}},<br /><br /><br />
                Ihr Terminwunsch kann leider nicht erf√ºllt werden.
              </p>
              <hr style="border-color: #f5f5f5; border-width: 1px; margin: 5px" />
              <p>Buchen Sie gleich einen neuen Termin. Das Team von {{ merchant.branch_name}} freut sich auf Ihren Besuch!</p>
              <table
                style="border-collapse: collapse; margin-top: 1em"
                width="100%"
              >
                <tbody>
                  <tr>
                    <td style="padding-top: 1em;" align="center">
                      <a
                        href="{{calendar_entry.booking_url}}"
                        style="
                          display: inline-block;
                          padding: 10px 20px;
                          background-color: #10766e;
                          color: white;
                          text-decoration: none;
                          border-radius: 5px;
                        "
                        >Ihr Termin</a
                      >
                    </td>
                  </tr>
                </tbody>
              </table>

              <table style="border-collapse: collapse" width="100%">
                <tbody>
                  <tr>
                    <td
                      style="width: 60px; vertical-align: middle"
                      align="center"
                    >
                    <p style="font-size: smaller">
                      {{merchant.branch_name}} <br>
                      {{merchant.address.street_address}}<br>
                      {{merchant.address.post_code}} {{merchant.address.city}}<br
                    </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </center>
